apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: custom-worker-kubelet
spec:
  autoSizingReserved: true
  machineConfigPoolSelector:
    matchLabels:
      managed.openshift.io/custom-worker-kubelet: ""
